package com.muyi.bigMonster.mapper;

import com.muyi.bigMonster.model.LiveVideoAttribute;
import com.muyi.bigMonster.model.LiveVideoAttributeExample;
import java.util.List;

import org.apache.ibatis.annotations.*;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Repository
public interface LiveVideoAttributeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_video_attribute
     *
     * @mbg.generated Fri May 22 19:26:03 CST 2020
     */
    long countByExample(LiveVideoAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_video_attribute
     *
     * @mbg.generated Fri May 22 19:26:03 CST 2020
     */
    int deleteByExample(LiveVideoAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_video_attribute
     *
     * @mbg.generated Fri May 22 19:26:03 CST 2020
     */
    @Delete({
        "delete from live_video_attribute",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_video_attribute
     *
     * @mbg.generated Fri May 22 19:26:03 CST 2020
     */
    @Insert({
        "insert into live_video_attribute (id, account_id, ",
        "fps, bitrate, gop, ",
        "quality, create_time, ",
        "update_time)",
        "values (#{id,jdbcType=INTEGER}, #{accountId,jdbcType=INTEGER}, ",
        "#{fps,jdbcType=INTEGER}, #{bitrate,jdbcType=INTEGER}, #{gop,jdbcType=INTEGER}, ",
        "#{quality,jdbcType=INTEGER}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{updateTime,jdbcType=TIMESTAMP})"
    })
    int insert(LiveVideoAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_video_attribute
     *
     * @mbg.generated Fri May 22 19:26:03 CST 2020
     */
    int insertSelective(LiveVideoAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_video_attribute
     *
     * @mbg.generated Fri May 22 19:26:03 CST 2020
     */
    List<LiveVideoAttribute> selectByExampleWithRowbounds(LiveVideoAttributeExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_video_attribute
     *
     * @mbg.generated Fri May 22 19:26:03 CST 2020
     */
    List<LiveVideoAttribute> selectByExample(LiveVideoAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_video_attribute
     *
     * @mbg.generated Fri May 22 19:26:03 CST 2020
     */
    @Select({
        "select",
        "id, account_id, fps, bitrate, gop, quality, create_time, update_time",
        "from live_video_attribute",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("com.muyi.bigMonster.mapper.LiveVideoAttributeMapper.BaseResultMap")
    LiveVideoAttribute selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_video_attribute
     *
     * @mbg.generated Fri May 22 19:26:03 CST 2020
     */
    int updateByExampleSelective(@Param("record") LiveVideoAttribute record, @Param("example") LiveVideoAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_video_attribute
     *
     * @mbg.generated Fri May 22 19:26:03 CST 2020
     */
    int updateByExample(@Param("record") LiveVideoAttribute record, @Param("example") LiveVideoAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_video_attribute
     *
     * @mbg.generated Fri May 22 19:26:03 CST 2020
     */
    int updateByPrimaryKeySelective(LiveVideoAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_video_attribute
     *
     * @mbg.generated Fri May 22 19:26:03 CST 2020
     */
    @Update({
        "update live_video_attribute",
        "set account_id = #{accountId,jdbcType=INTEGER},",
          "fps = #{fps,jdbcType=INTEGER},",
          "bitrate = #{bitrate,jdbcType=INTEGER},",
          "gop = #{gop,jdbcType=INTEGER},",
          "quality = #{quality,jdbcType=INTEGER},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(LiveVideoAttribute record);
}
