# 服务基础配置
server:
  servlet:
    context-path: /monster
  port: 9999

# xconf zk地址
xconf:
  address: 47.99.2.51:2181,47.99.2.51:2182,47.99.2.51:2183

# dubbo配置
dubbo:
  application:
    name: big-monster
    author: muyi
  registry:
    protocol: zookeeper
    address: 47.99.2.51:2181,47.99.2.51:2182,47.99.2.51:2183
    register: false
  consumer:
    timeout: 5000

spring:
  application:
    name: big-monster
  #数据库连接相关配置
  datasource:
    daily1:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://rm-bp11d50m31tbdlv0h2o.mysql.rds.aliyuncs.com:3306/qamanager
      username: muyi
      password: k2Tp4SF834phWKO1
    daily2drds:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://drdshbga3gjsy83cpublic.drds.aliyuncs.com:3306/promotion_platform
      username: muyi
      password: k2Tp4SF834phWKO1
    daily3:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://rm-bp1td245ijdcjcrz51o.mysql.rds.aliyuncs.com:3306/search_platform
      username: muyi
      password: k2Tp4SF834phWKO1

# mybatis
mybatis:
  mapper-locations: classpath*:com/muyi/bigMonster/mapper/**/*.xml  #
  configuration:
    map-underscore-to-camel-case: true

