package com.muyi.bigMonster.mapper.zebra;

import com.muyi.bigMonster.model.zebra.LiveVideoAttribute;
import com.muyi.bigMonster.model.zebra.LiveVideoAttributeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface LiveVideoAttributeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_video_attribute
     *
     * @mbg.generated Fri May 22 18:06:40 CST 2020
     */
    long countByExample(LiveVideoAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_video_attribute
     *
     * @mbg.generated Fri May 22 18:06:40 CST 2020
     */
    int deleteByExample(LiveVideoAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_video_attribute
     *
     * @mbg.generated Fri May 22 18:06:40 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_video_attribute
     *
     * @mbg.generated Fri May 22 18:06:40 CST 2020
     */
    int insert(LiveVideoAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_video_attribute
     *
     * @mbg.generated Fri May 22 18:06:40 CST 2020
     */
    int insertSelective(LiveVideoAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_video_attribute
     *
     * @mbg.generated Fri May 22 18:06:40 CST 2020
     */
    List<LiveVideoAttribute> selectByExampleWithRowbounds(LiveVideoAttributeExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_video_attribute
     *
     * @mbg.generated Fri May 22 18:06:40 CST 2020
     */
    List<LiveVideoAttribute> selectByExample(LiveVideoAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_video_attribute
     *
     * @mbg.generated Fri May 22 18:06:40 CST 2020
     */
    LiveVideoAttribute selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_video_attribute
     *
     * @mbg.generated Fri May 22 18:06:40 CST 2020
     */
    int updateByExampleSelective(@Param("record") LiveVideoAttribute record, @Param("example") LiveVideoAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_video_attribute
     *
     * @mbg.generated Fri May 22 18:06:40 CST 2020
     */
    int updateByExample(@Param("record") LiveVideoAttribute record, @Param("example") LiveVideoAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_video_attribute
     *
     * @mbg.generated Fri May 22 18:06:40 CST 2020
     */
    int updateByPrimaryKeySelective(LiveVideoAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_video_attribute
     *
     * @mbg.generated Fri May 22 18:06:40 CST 2020
     */
    int updateByPrimaryKey(LiveVideoAttribute record);
}