package com.muyi.bigMonster.mapper.daily3;

import com.muyi.bigMonster.model.daily3.GoodsIndexData;
import com.muyi.bigMonster.model.daily3.GoodsIndexDataExample;
import com.muyi.bigMonster.model.daily3.GoodsIndexDataWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.session.RowBounds;
import org.apache.ibatis.type.JdbcType;

public interface GoodsIndexDataMapper {
    @SelectProvider(type=GoodsIndexDataSqlProvider.class, method="countByExample")
    long countByExample(GoodsIndexDataExample example);

    @DeleteProvider(type=GoodsIndexDataSqlProvider.class, method="deleteByExample")
    int deleteByExample(GoodsIndexDataExample example);

    @Delete({
        "delete from goods_index_data",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    @Insert({
        "insert into goods_index_data (id, item_id, ",
        "long_title, short_title, ",
        "channel, original_channel, ",
        "shelf, status, item_type, ",
        "item_sub_type, first_shelf_time, ",
        "item_create_time, item_deliver_area_type, ",
        "white_image_url, white_image_width, ",
        "white_image_height, major_image_url, ",
        "major_image_width, major_image_height, ",
        "brand_id, brand_cn_name, ",
        "brand_en_name, brand_state_id, ",
        "brand_state_name, brand_country_flag_url, ",
        "category_id, category_id_path, ",
        "category_name, category_path_name, ",
        "search_tags, goods_tags, ",
        "goods_properties, shop_id, ",
        "shop_name, shop_class_id, ",
        "shop_type, registration_address_type, ",
        "shop_level, shop_major_category_ids, ",
        "shop_gmv_30, shop_gmv_90, ",
        "shop_aftersale_rate_30, shop_open_days, ",
        "shop_dsr, shop_30_days_sales_volume, ",
        "activity_ids, activity_blacklist, ",
        "shop_activity_info, shop_warm_activity_info, ",
        "shop_part_activity_ids, shop_invest_part_activity_ids, ",
        "shop_invest_activity_ids, cross_shop_activity_ids, ",
        "cross_shop_activity_info, allowance_activity_ids, ",
        "original_price, price, ",
        "big_promotion_price, daily_price, ",
        "vip_price, big_promotion_vip_price, ",
        "daily_vip_price, market_price, ",
        "commission_total, commission, ",
        "brokerage, lowest_price_last_7_days, ",
        "lowest_price_last_15_days, lowest_price_last_30_days, ",
        "in_big_promotion, goods_7_days_sales_volume, ",
        "goods_30_days_sales_volume, goods_60_days_sales_volume, ",
        "goods_gmv_7, goods_gmv_30, ",
        "goods_gmv_60, goods_dsr, ",
        "click_conver_rate_30, purchase_conver_rate_30, ",
        "pay_conver_rate_30, reputation_rate, ",
        "reputation_rate30, buyer_number, ",
        "score, weight, prediction_score, ",
        "item_score, in_black_list, ",
        "in_stock, in_feed, sku_num, ",
        "deleted, create_time, ",
        "update_time, anchor_earning, ",
        "anchor_commission, channel_data, ",
        "shop_tags, activity_tags, ",
        "whole_sale_discounts, big_promotion_price_info, ",
        "advance_sale_info, embedding)",
        "values (#{id,jdbcType=BIGINT}, #{itemId,jdbcType=BIGINT}, ",
        "#{longTitle,jdbcType=VARCHAR}, #{shortTitle,jdbcType=VARCHAR}, ",
        "#{channel,jdbcType=TINYINT}, #{originalChannel,jdbcType=TINYINT}, ",
        "#{shelf,jdbcType=TINYINT}, #{status,jdbcType=TINYINT}, #{itemType,jdbcType=TINYINT}, ",
        "#{itemSubType,jdbcType=TINYINT}, #{firstShelfTime,jdbcType=BIGINT}, ",
        "#{itemCreateTime,jdbcType=TIMESTAMP}, #{itemDeliverAreaType,jdbcType=BIT}, ",
        "#{whiteImageUrl,jdbcType=VARCHAR}, #{whiteImageWidth,jdbcType=INTEGER}, ",
        "#{whiteImageHeight,jdbcType=INTEGER}, #{majorImageUrl,jdbcType=VARCHAR}, ",
        "#{majorImageWidth,jdbcType=INTEGER}, #{majorImageHeight,jdbcType=INTEGER}, ",
        "#{brandId,jdbcType=INTEGER}, #{brandCnName,jdbcType=VARCHAR}, ",
        "#{brandEnName,jdbcType=VARCHAR}, #{brandStateId,jdbcType=INTEGER}, ",
        "#{brandStateName,jdbcType=VARCHAR}, #{brandCountryFlagUrl,jdbcType=VARCHAR}, ",
        "#{categoryId,jdbcType=INTEGER}, #{categoryIdPath,jdbcType=VARCHAR}, ",
        "#{categoryName,jdbcType=VARCHAR}, #{categoryPathName,jdbcType=VARCHAR}, ",
        "#{searchTags,jdbcType=VARCHAR}, #{goodsTags,jdbcType=VARCHAR}, ",
        "#{goodsProperties,jdbcType=VARCHAR}, #{shopId,jdbcType=BIGINT}, ",
        "#{shopName,jdbcType=VARCHAR}, #{shopClassId,jdbcType=VARCHAR}, ",
        "#{shopType,jdbcType=BIT}, #{registrationAddressType,jdbcType=BIT}, ",
        "#{shopLevel,jdbcType=BIT}, #{shopMajorCategoryIds,jdbcType=VARCHAR}, ",
        "#{shopGmv30,jdbcType=DECIMAL}, #{shopGmv90,jdbcType=DECIMAL}, ",
        "#{shopAftersaleRate30,jdbcType=DECIMAL}, #{shopOpenDays,jdbcType=INTEGER}, ",
        "#{shopDsr,jdbcType=DECIMAL}, #{shop30DaysSalesVolume,jdbcType=BIGINT}, ",
        "#{activityIds,jdbcType=VARCHAR}, #{activityBlacklist,jdbcType=VARCHAR}, ",
        "#{shopActivityInfo,jdbcType=VARCHAR}, #{shopWarmActivityInfo,jdbcType=VARCHAR}, ",
        "#{shopPartActivityIds,jdbcType=VARCHAR}, #{shopInvestPartActivityIds,jdbcType=VARCHAR}, ",
        "#{shopInvestActivityIds,jdbcType=VARCHAR}, #{crossShopActivityIds,jdbcType=VARCHAR}, ",
        "#{crossShopActivityInfo,jdbcType=VARCHAR}, #{allowanceActivityIds,jdbcType=VARCHAR}, ",
        "#{originalPrice,jdbcType=BIGINT}, #{price,jdbcType=BIGINT}, ",
        "#{bigPromotionPrice,jdbcType=BIGINT}, #{dailyPrice,jdbcType=BIGINT}, ",
        "#{vipPrice,jdbcType=BIGINT}, #{bigPromotionVipPrice,jdbcType=BIGINT}, ",
        "#{dailyVipPrice,jdbcType=BIGINT}, #{marketPrice,jdbcType=INTEGER}, ",
        "#{commissionTotal,jdbcType=BIGINT}, #{commission,jdbcType=BIGINT}, ",
        "#{brokerage,jdbcType=DECIMAL}, #{lowestPriceLast7Days,jdbcType=BIGINT}, ",
        "#{lowestPriceLast15Days,jdbcType=BIGINT}, #{lowestPriceLast30Days,jdbcType=BIGINT}, ",
        "#{inBigPromotion,jdbcType=TINYINT}, #{goods7DaysSalesVolume,jdbcType=BIGINT}, ",
        "#{goods30DaysSalesVolume,jdbcType=BIGINT}, #{goods60DaysSalesVolume,jdbcType=BIGINT}, ",
        "#{goodsGmv7,jdbcType=DECIMAL}, #{goodsGmv30,jdbcType=DECIMAL}, ",
        "#{goodsGmv60,jdbcType=DECIMAL}, #{goodsDsr,jdbcType=DECIMAL}, ",
        "#{clickConverRate30,jdbcType=DECIMAL}, #{purchaseConverRate30,jdbcType=DECIMAL}, ",
        "#{payConverRate30,jdbcType=DECIMAL}, #{reputationRate,jdbcType=DECIMAL}, ",
        "#{reputationRate30,jdbcType=DECIMAL}, #{buyerNumber,jdbcType=BIGINT}, ",
        "#{score,jdbcType=DECIMAL}, #{weight,jdbcType=INTEGER}, #{predictionScore,jdbcType=DOUBLE}, ",
        "#{itemScore,jdbcType=DOUBLE}, #{inBlackList,jdbcType=BIT}, ",
        "#{inStock,jdbcType=BIT}, #{inFeed,jdbcType=TINYINT}, #{skuNum,jdbcType=SMALLINT}, ",
        "#{deleted,jdbcType=BIT}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{updateTime,jdbcType=TIMESTAMP}, #{anchorEarning,jdbcType=BIGINT}, ",
        "#{anchorCommission,jdbcType=DECIMAL}, #{channelData,jdbcType=LONGVARCHAR}, ",
        "#{shopTags,jdbcType=LONGVARCHAR}, #{activityTags,jdbcType=LONGVARCHAR}, ",
        "#{wholeSaleDiscounts,jdbcType=LONGVARCHAR}, #{bigPromotionPriceInfo,jdbcType=LONGVARCHAR}, ",
        "#{advanceSaleInfo,jdbcType=LONGVARCHAR}, #{embedding,jdbcType=LONGVARCHAR})"
    })
    int insert(GoodsIndexDataWithBLOBs record);

    @InsertProvider(type=GoodsIndexDataSqlProvider.class, method="insertSelective")
    int insertSelective(GoodsIndexDataWithBLOBs record);

    @SelectProvider(type=GoodsIndexDataSqlProvider.class, method="selectByExampleWithBLOBs")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="item_id", property="itemId", jdbcType=JdbcType.BIGINT),
        @Result(column="long_title", property="longTitle", jdbcType=JdbcType.VARCHAR),
        @Result(column="short_title", property="shortTitle", jdbcType=JdbcType.VARCHAR),
        @Result(column="channel", property="channel", jdbcType=JdbcType.TINYINT),
        @Result(column="original_channel", property="originalChannel", jdbcType=JdbcType.TINYINT),
        @Result(column="shelf", property="shelf", jdbcType=JdbcType.TINYINT),
        @Result(column="status", property="status", jdbcType=JdbcType.TINYINT),
        @Result(column="item_type", property="itemType", jdbcType=JdbcType.TINYINT),
        @Result(column="item_sub_type", property="itemSubType", jdbcType=JdbcType.TINYINT),
        @Result(column="first_shelf_time", property="firstShelfTime", jdbcType=JdbcType.BIGINT),
        @Result(column="item_create_time", property="itemCreateTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="item_deliver_area_type", property="itemDeliverAreaType", jdbcType=JdbcType.BIT),
        @Result(column="white_image_url", property="whiteImageUrl", jdbcType=JdbcType.VARCHAR),
        @Result(column="white_image_width", property="whiteImageWidth", jdbcType=JdbcType.INTEGER),
        @Result(column="white_image_height", property="whiteImageHeight", jdbcType=JdbcType.INTEGER),
        @Result(column="major_image_url", property="majorImageUrl", jdbcType=JdbcType.VARCHAR),
        @Result(column="major_image_width", property="majorImageWidth", jdbcType=JdbcType.INTEGER),
        @Result(column="major_image_height", property="majorImageHeight", jdbcType=JdbcType.INTEGER),
        @Result(column="brand_id", property="brandId", jdbcType=JdbcType.INTEGER),
        @Result(column="brand_cn_name", property="brandCnName", jdbcType=JdbcType.VARCHAR),
        @Result(column="brand_en_name", property="brandEnName", jdbcType=JdbcType.VARCHAR),
        @Result(column="brand_state_id", property="brandStateId", jdbcType=JdbcType.INTEGER),
        @Result(column="brand_state_name", property="brandStateName", jdbcType=JdbcType.VARCHAR),
        @Result(column="brand_country_flag_url", property="brandCountryFlagUrl", jdbcType=JdbcType.VARCHAR),
        @Result(column="category_id", property="categoryId", jdbcType=JdbcType.INTEGER),
        @Result(column="category_id_path", property="categoryIdPath", jdbcType=JdbcType.VARCHAR),
        @Result(column="category_name", property="categoryName", jdbcType=JdbcType.VARCHAR),
        @Result(column="category_path_name", property="categoryPathName", jdbcType=JdbcType.VARCHAR),
        @Result(column="search_tags", property="searchTags", jdbcType=JdbcType.VARCHAR),
        @Result(column="goods_tags", property="goodsTags", jdbcType=JdbcType.VARCHAR),
        @Result(column="goods_properties", property="goodsProperties", jdbcType=JdbcType.VARCHAR),
        @Result(column="shop_id", property="shopId", jdbcType=JdbcType.BIGINT),
        @Result(column="shop_name", property="shopName", jdbcType=JdbcType.VARCHAR),
        @Result(column="shop_class_id", property="shopClassId", jdbcType=JdbcType.VARCHAR),
        @Result(column="shop_type", property="shopType", jdbcType=JdbcType.BIT),
        @Result(column="registration_address_type", property="registrationAddressType", jdbcType=JdbcType.BIT),
        @Result(column="shop_level", property="shopLevel", jdbcType=JdbcType.BIT),
        @Result(column="shop_major_category_ids", property="shopMajorCategoryIds", jdbcType=JdbcType.VARCHAR),
        @Result(column="shop_gmv_30", property="shopGmv30", jdbcType=JdbcType.DECIMAL),
        @Result(column="shop_gmv_90", property="shopGmv90", jdbcType=JdbcType.DECIMAL),
        @Result(column="shop_aftersale_rate_30", property="shopAftersaleRate30", jdbcType=JdbcType.DECIMAL),
        @Result(column="shop_open_days", property="shopOpenDays", jdbcType=JdbcType.INTEGER),
        @Result(column="shop_dsr", property="shopDsr", jdbcType=JdbcType.DECIMAL),
        @Result(column="shop_30_days_sales_volume", property="shop30DaysSalesVolume", jdbcType=JdbcType.BIGINT),
        @Result(column="activity_ids", property="activityIds", jdbcType=JdbcType.VARCHAR),
        @Result(column="activity_blacklist", property="activityBlacklist", jdbcType=JdbcType.VARCHAR),
        @Result(column="shop_activity_info", property="shopActivityInfo", jdbcType=JdbcType.VARCHAR),
        @Result(column="shop_warm_activity_info", property="shopWarmActivityInfo", jdbcType=JdbcType.VARCHAR),
        @Result(column="shop_part_activity_ids", property="shopPartActivityIds", jdbcType=JdbcType.VARCHAR),
        @Result(column="shop_invest_part_activity_ids", property="shopInvestPartActivityIds", jdbcType=JdbcType.VARCHAR),
        @Result(column="shop_invest_activity_ids", property="shopInvestActivityIds", jdbcType=JdbcType.VARCHAR),
        @Result(column="cross_shop_activity_ids", property="crossShopActivityIds", jdbcType=JdbcType.VARCHAR),
        @Result(column="cross_shop_activity_info", property="crossShopActivityInfo", jdbcType=JdbcType.VARCHAR),
        @Result(column="allowance_activity_ids", property="allowanceActivityIds", jdbcType=JdbcType.VARCHAR),
        @Result(column="original_price", property="originalPrice", jdbcType=JdbcType.BIGINT),
        @Result(column="price", property="price", jdbcType=JdbcType.BIGINT),
        @Result(column="big_promotion_price", property="bigPromotionPrice", jdbcType=JdbcType.BIGINT),
        @Result(column="daily_price", property="dailyPrice", jdbcType=JdbcType.BIGINT),
        @Result(column="vip_price", property="vipPrice", jdbcType=JdbcType.BIGINT),
        @Result(column="big_promotion_vip_price", property="bigPromotionVipPrice", jdbcType=JdbcType.BIGINT),
        @Result(column="daily_vip_price", property="dailyVipPrice", jdbcType=JdbcType.BIGINT),
        @Result(column="market_price", property="marketPrice", jdbcType=JdbcType.INTEGER),
        @Result(column="commission_total", property="commissionTotal", jdbcType=JdbcType.BIGINT),
        @Result(column="commission", property="commission", jdbcType=JdbcType.BIGINT),
        @Result(column="brokerage", property="brokerage", jdbcType=JdbcType.DECIMAL),
        @Result(column="lowest_price_last_7_days", property="lowestPriceLast7Days", jdbcType=JdbcType.BIGINT),
        @Result(column="lowest_price_last_15_days", property="lowestPriceLast15Days", jdbcType=JdbcType.BIGINT),
        @Result(column="lowest_price_last_30_days", property="lowestPriceLast30Days", jdbcType=JdbcType.BIGINT),
        @Result(column="in_big_promotion", property="inBigPromotion", jdbcType=JdbcType.TINYINT),
        @Result(column="goods_7_days_sales_volume", property="goods7DaysSalesVolume", jdbcType=JdbcType.BIGINT),
        @Result(column="goods_30_days_sales_volume", property="goods30DaysSalesVolume", jdbcType=JdbcType.BIGINT),
        @Result(column="goods_60_days_sales_volume", property="goods60DaysSalesVolume", jdbcType=JdbcType.BIGINT),
        @Result(column="goods_gmv_7", property="goodsGmv7", jdbcType=JdbcType.DECIMAL),
        @Result(column="goods_gmv_30", property="goodsGmv30", jdbcType=JdbcType.DECIMAL),
        @Result(column="goods_gmv_60", property="goodsGmv60", jdbcType=JdbcType.DECIMAL),
        @Result(column="goods_dsr", property="goodsDsr", jdbcType=JdbcType.DECIMAL),
        @Result(column="click_conver_rate_30", property="clickConverRate30", jdbcType=JdbcType.DECIMAL),
        @Result(column="purchase_conver_rate_30", property="purchaseConverRate30", jdbcType=JdbcType.DECIMAL),
        @Result(column="pay_conver_rate_30", property="payConverRate30", jdbcType=JdbcType.DECIMAL),
        @Result(column="reputation_rate", property="reputationRate", jdbcType=JdbcType.DECIMAL),
        @Result(column="reputation_rate30", property="reputationRate30", jdbcType=JdbcType.DECIMAL),
        @Result(column="buyer_number", property="buyerNumber", jdbcType=JdbcType.BIGINT),
        @Result(column="score", property="score", jdbcType=JdbcType.DECIMAL),
        @Result(column="weight", property="weight", jdbcType=JdbcType.INTEGER),
        @Result(column="prediction_score", property="predictionScore", jdbcType=JdbcType.DOUBLE),
        @Result(column="item_score", property="itemScore", jdbcType=JdbcType.DOUBLE),
        @Result(column="in_black_list", property="inBlackList", jdbcType=JdbcType.BIT),
        @Result(column="in_stock", property="inStock", jdbcType=JdbcType.BIT),
        @Result(column="in_feed", property="inFeed", jdbcType=JdbcType.TINYINT),
        @Result(column="sku_num", property="skuNum", jdbcType=JdbcType.SMALLINT),
        @Result(column="deleted", property="deleted", jdbcType=JdbcType.BIT),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="anchor_earning", property="anchorEarning", jdbcType=JdbcType.BIGINT),
        @Result(column="anchor_commission", property="anchorCommission", jdbcType=JdbcType.DECIMAL),
        @Result(column="channel_data", property="channelData", jdbcType=JdbcType.LONGVARCHAR),
        @Result(column="shop_tags", property="shopTags", jdbcType=JdbcType.LONGVARCHAR),
        @Result(column="activity_tags", property="activityTags", jdbcType=JdbcType.LONGVARCHAR),
        @Result(column="whole_sale_discounts", property="wholeSaleDiscounts", jdbcType=JdbcType.LONGVARCHAR),
        @Result(column="big_promotion_price_info", property="bigPromotionPriceInfo", jdbcType=JdbcType.LONGVARCHAR),
        @Result(column="advance_sale_info", property="advanceSaleInfo", jdbcType=JdbcType.LONGVARCHAR),
        @Result(column="embedding", property="embedding", jdbcType=JdbcType.LONGVARCHAR)
    })
    List<GoodsIndexDataWithBLOBs> selectByExampleWithBLOBsWithRowbounds(GoodsIndexDataExample example, RowBounds rowBounds);

    @SelectProvider(type=GoodsIndexDataSqlProvider.class, method="selectByExampleWithBLOBs")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="item_id", property="itemId", jdbcType=JdbcType.BIGINT),
        @Result(column="long_title", property="longTitle", jdbcType=JdbcType.VARCHAR),
        @Result(column="short_title", property="shortTitle", jdbcType=JdbcType.VARCHAR),
        @Result(column="channel", property="channel", jdbcType=JdbcType.TINYINT),
        @Result(column="original_channel", property="originalChannel", jdbcType=JdbcType.TINYINT),
        @Result(column="shelf", property="shelf", jdbcType=JdbcType.TINYINT),
        @Result(column="status", property="status", jdbcType=JdbcType.TINYINT),
        @Result(column="item_type", property="itemType", jdbcType=JdbcType.TINYINT),
        @Result(column="item_sub_type", property="itemSubType", jdbcType=JdbcType.TINYINT),
        @Result(column="first_shelf_time", property="firstShelfTime", jdbcType=JdbcType.BIGINT),
        @Result(column="item_create_time", property="itemCreateTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="item_deliver_area_type", property="itemDeliverAreaType", jdbcType=JdbcType.BIT),
        @Result(column="white_image_url", property="whiteImageUrl", jdbcType=JdbcType.VARCHAR),
        @Result(column="white_image_width", property="whiteImageWidth", jdbcType=JdbcType.INTEGER),
        @Result(column="white_image_height", property="whiteImageHeight", jdbcType=JdbcType.INTEGER),
        @Result(column="major_image_url", property="majorImageUrl", jdbcType=JdbcType.VARCHAR),
        @Result(column="major_image_width", property="majorImageWidth", jdbcType=JdbcType.INTEGER),
        @Result(column="major_image_height", property="majorImageHeight", jdbcType=JdbcType.INTEGER),
        @Result(column="brand_id", property="brandId", jdbcType=JdbcType.INTEGER),
        @Result(column="brand_cn_name", property="brandCnName", jdbcType=JdbcType.VARCHAR),
        @Result(column="brand_en_name", property="brandEnName", jdbcType=JdbcType.VARCHAR),
        @Result(column="brand_state_id", property="brandStateId", jdbcType=JdbcType.INTEGER),
        @Result(column="brand_state_name", property="brandStateName", jdbcType=JdbcType.VARCHAR),
        @Result(column="brand_country_flag_url", property="brandCountryFlagUrl", jdbcType=JdbcType.VARCHAR),
        @Result(column="category_id", property="categoryId", jdbcType=JdbcType.INTEGER),
        @Result(column="category_id_path", property="categoryIdPath", jdbcType=JdbcType.VARCHAR),
        @Result(column="category_name", property="categoryName", jdbcType=JdbcType.VARCHAR),
        @Result(column="category_path_name", property="categoryPathName", jdbcType=JdbcType.VARCHAR),
        @Result(column="search_tags", property="searchTags", jdbcType=JdbcType.VARCHAR),
        @Result(column="goods_tags", property="goodsTags", jdbcType=JdbcType.VARCHAR),
        @Result(column="goods_properties", property="goodsProperties", jdbcType=JdbcType.VARCHAR),
        @Result(column="shop_id", property="shopId", jdbcType=JdbcType.BIGINT),
        @Result(column="shop_name", property="shopName", jdbcType=JdbcType.VARCHAR),
        @Result(column="shop_class_id", property="shopClassId", jdbcType=JdbcType.VARCHAR),
        @Result(column="shop_type", property="shopType", jdbcType=JdbcType.BIT),
        @Result(column="registration_address_type", property="registrationAddressType", jdbcType=JdbcType.BIT),
        @Result(column="shop_level", property="shopLevel", jdbcType=JdbcType.BIT),
        @Result(column="shop_major_category_ids", property="shopMajorCategoryIds", jdbcType=JdbcType.VARCHAR),
        @Result(column="shop_gmv_30", property="shopGmv30", jdbcType=JdbcType.DECIMAL),
        @Result(column="shop_gmv_90", property="shopGmv90", jdbcType=JdbcType.DECIMAL),
        @Result(column="shop_aftersale_rate_30", property="shopAftersaleRate30", jdbcType=JdbcType.DECIMAL),
        @Result(column="shop_open_days", property="shopOpenDays", jdbcType=JdbcType.INTEGER),
        @Result(column="shop_dsr", property="shopDsr", jdbcType=JdbcType.DECIMAL),
        @Result(column="shop_30_days_sales_volume", property="shop30DaysSalesVolume", jdbcType=JdbcType.BIGINT),
        @Result(column="activity_ids", property="activityIds", jdbcType=JdbcType.VARCHAR),
        @Result(column="activity_blacklist", property="activityBlacklist", jdbcType=JdbcType.VARCHAR),
        @Result(column="shop_activity_info", property="shopActivityInfo", jdbcType=JdbcType.VARCHAR),
        @Result(column="shop_warm_activity_info", property="shopWarmActivityInfo", jdbcType=JdbcType.VARCHAR),
        @Result(column="shop_part_activity_ids", property="shopPartActivityIds", jdbcType=JdbcType.VARCHAR),
        @Result(column="shop_invest_part_activity_ids", property="shopInvestPartActivityIds", jdbcType=JdbcType.VARCHAR),
        @Result(column="shop_invest_activity_ids", property="shopInvestActivityIds", jdbcType=JdbcType.VARCHAR),
        @Result(column="cross_shop_activity_ids", property="crossShopActivityIds", jdbcType=JdbcType.VARCHAR),
        @Result(column="cross_shop_activity_info", property="crossShopActivityInfo", jdbcType=JdbcType.VARCHAR),
        @Result(column="allowance_activity_ids", property="allowanceActivityIds", jdbcType=JdbcType.VARCHAR),
        @Result(column="original_price", property="originalPrice", jdbcType=JdbcType.BIGINT),
        @Result(column="price", property="price", jdbcType=JdbcType.BIGINT),
        @Result(column="big_promotion_price", property="bigPromotionPrice", jdbcType=JdbcType.BIGINT),
        @Result(column="daily_price", property="dailyPrice", jdbcType=JdbcType.BIGINT),
        @Result(column="vip_price", property="vipPrice", jdbcType=JdbcType.BIGINT),
        @Result(column="big_promotion_vip_price", property="bigPromotionVipPrice", jdbcType=JdbcType.BIGINT),
        @Result(column="daily_vip_price", property="dailyVipPrice", jdbcType=JdbcType.BIGINT),
        @Result(column="market_price", property="marketPrice", jdbcType=JdbcType.INTEGER),
        @Result(column="commission_total", property="commissionTotal", jdbcType=JdbcType.BIGINT),
        @Result(column="commission", property="commission", jdbcType=JdbcType.BIGINT),
        @Result(column="brokerage", property="brokerage", jdbcType=JdbcType.DECIMAL),
        @Result(column="lowest_price_last_7_days", property="lowestPriceLast7Days", jdbcType=JdbcType.BIGINT),
        @Result(column="lowest_price_last_15_days", property="lowestPriceLast15Days", jdbcType=JdbcType.BIGINT),
        @Result(column="lowest_price_last_30_days", property="lowestPriceLast30Days", jdbcType=JdbcType.BIGINT),
        @Result(column="in_big_promotion", property="inBigPromotion", jdbcType=JdbcType.TINYINT),
        @Result(column="goods_7_days_sales_volume", property="goods7DaysSalesVolume", jdbcType=JdbcType.BIGINT),
        @Result(column="goods_30_days_sales_volume", property="goods30DaysSalesVolume", jdbcType=JdbcType.BIGINT),
        @Result(column="goods_60_days_sales_volume", property="goods60DaysSalesVolume", jdbcType=JdbcType.BIGINT),
        @Result(column="goods_gmv_7", property="goodsGmv7", jdbcType=JdbcType.DECIMAL),
        @Result(column="goods_gmv_30", property="goodsGmv30", jdbcType=JdbcType.DECIMAL),
        @Result(column="goods_gmv_60", property="goodsGmv60", jdbcType=JdbcType.DECIMAL),
        @Result(column="goods_dsr", property="goodsDsr", jdbcType=JdbcType.DECIMAL),
        @Result(column="click_conver_rate_30", property="clickConverRate30", jdbcType=JdbcType.DECIMAL),
        @Result(column="purchase_conver_rate_30", property="purchaseConverRate30", jdbcType=JdbcType.DECIMAL),
        @Result(column="pay_conver_rate_30", property="payConverRate30", jdbcType=JdbcType.DECIMAL),
        @Result(column="reputation_rate", property="reputationRate", jdbcType=JdbcType.DECIMAL),
        @Result(column="reputation_rate30", property="reputationRate30", jdbcType=JdbcType.DECIMAL),
        @Result(column="buyer_number", property="buyerNumber", jdbcType=JdbcType.BIGINT),
        @Result(column="score", property="score", jdbcType=JdbcType.DECIMAL),
        @Result(column="weight", property="weight", jdbcType=JdbcType.INTEGER),
        @Result(column="prediction_score", property="predictionScore", jdbcType=JdbcType.DOUBLE),
        @Result(column="item_score", property="itemScore", jdbcType=JdbcType.DOUBLE),
        @Result(column="in_black_list", property="inBlackList", jdbcType=JdbcType.BIT),
        @Result(column="in_stock", property="inStock", jdbcType=JdbcType.BIT),
        @Result(column="in_feed", property="inFeed", jdbcType=JdbcType.TINYINT),
        @Result(column="sku_num", property="skuNum", jdbcType=JdbcType.SMALLINT),
        @Result(column="deleted", property="deleted", jdbcType=JdbcType.BIT),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="anchor_earning", property="anchorEarning", jdbcType=JdbcType.BIGINT),
        @Result(column="anchor_commission", property="anchorCommission", jdbcType=JdbcType.DECIMAL),
        @Result(column="channel_data", property="channelData", jdbcType=JdbcType.LONGVARCHAR),
        @Result(column="shop_tags", property="shopTags", jdbcType=JdbcType.LONGVARCHAR),
        @Result(column="activity_tags", property="activityTags", jdbcType=JdbcType.LONGVARCHAR),
        @Result(column="whole_sale_discounts", property="wholeSaleDiscounts", jdbcType=JdbcType.LONGVARCHAR),
        @Result(column="big_promotion_price_info", property="bigPromotionPriceInfo", jdbcType=JdbcType.LONGVARCHAR),
        @Result(column="advance_sale_info", property="advanceSaleInfo", jdbcType=JdbcType.LONGVARCHAR),
        @Result(column="embedding", property="embedding", jdbcType=JdbcType.LONGVARCHAR)
    })
    List<GoodsIndexDataWithBLOBs> selectByExampleWithBLOBs(GoodsIndexDataExample example);

    @SelectProvider(type=GoodsIndexDataSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="item_id", property="itemId", jdbcType=JdbcType.BIGINT),
        @Result(column="long_title", property="longTitle", jdbcType=JdbcType.VARCHAR),
        @Result(column="short_title", property="shortTitle", jdbcType=JdbcType.VARCHAR),
        @Result(column="channel", property="channel", jdbcType=JdbcType.TINYINT),
        @Result(column="original_channel", property="originalChannel", jdbcType=JdbcType.TINYINT),
        @Result(column="shelf", property="shelf", jdbcType=JdbcType.TINYINT),
        @Result(column="status", property="status", jdbcType=JdbcType.TINYINT),
        @Result(column="item_type", property="itemType", jdbcType=JdbcType.TINYINT),
        @Result(column="item_sub_type", property="itemSubType", jdbcType=JdbcType.TINYINT),
        @Result(column="first_shelf_time", property="firstShelfTime", jdbcType=JdbcType.BIGINT),
        @Result(column="item_create_time", property="itemCreateTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="item_deliver_area_type", property="itemDeliverAreaType", jdbcType=JdbcType.BIT),
        @Result(column="white_image_url", property="whiteImageUrl", jdbcType=JdbcType.VARCHAR),
        @Result(column="white_image_width", property="whiteImageWidth", jdbcType=JdbcType.INTEGER),
        @Result(column="white_image_height", property="whiteImageHeight", jdbcType=JdbcType.INTEGER),
        @Result(column="major_image_url", property="majorImageUrl", jdbcType=JdbcType.VARCHAR),
        @Result(column="major_image_width", property="majorImageWidth", jdbcType=JdbcType.INTEGER),
        @Result(column="major_image_height", property="majorImageHeight", jdbcType=JdbcType.INTEGER),
        @Result(column="brand_id", property="brandId", jdbcType=JdbcType.INTEGER),
        @Result(column="brand_cn_name", property="brandCnName", jdbcType=JdbcType.VARCHAR),
        @Result(column="brand_en_name", property="brandEnName", jdbcType=JdbcType.VARCHAR),
        @Result(column="brand_state_id", property="brandStateId", jdbcType=JdbcType.INTEGER),
        @Result(column="brand_state_name", property="brandStateName", jdbcType=JdbcType.VARCHAR),
        @Result(column="brand_country_flag_url", property="brandCountryFlagUrl", jdbcType=JdbcType.VARCHAR),
        @Result(column="category_id", property="categoryId", jdbcType=JdbcType.INTEGER),
        @Result(column="category_id_path", property="categoryIdPath", jdbcType=JdbcType.VARCHAR),
        @Result(column="category_name", property="categoryName", jdbcType=JdbcType.VARCHAR),
        @Result(column="category_path_name", property="categoryPathName", jdbcType=JdbcType.VARCHAR),
        @Result(column="search_tags", property="searchTags", jdbcType=JdbcType.VARCHAR),
        @Result(column="goods_tags", property="goodsTags", jdbcType=JdbcType.VARCHAR),
        @Result(column="goods_properties", property="goodsProperties", jdbcType=JdbcType.VARCHAR),
        @Result(column="shop_id", property="shopId", jdbcType=JdbcType.BIGINT),
        @Result(column="shop_name", property="shopName", jdbcType=JdbcType.VARCHAR),
        @Result(column="shop_class_id", property="shopClassId", jdbcType=JdbcType.VARCHAR),
        @Result(column="shop_type", property="shopType", jdbcType=JdbcType.BIT),
        @Result(column="registration_address_type", property="registrationAddressType", jdbcType=JdbcType.BIT),
        @Result(column="shop_level", property="shopLevel", jdbcType=JdbcType.BIT),
        @Result(column="shop_major_category_ids", property="shopMajorCategoryIds", jdbcType=JdbcType.VARCHAR),
        @Result(column="shop_gmv_30", property="shopGmv30", jdbcType=JdbcType.DECIMAL),
        @Result(column="shop_gmv_90", property="shopGmv90", jdbcType=JdbcType.DECIMAL),
        @Result(column="shop_aftersale_rate_30", property="shopAftersaleRate30", jdbcType=JdbcType.DECIMAL),
        @Result(column="shop_open_days", property="shopOpenDays", jdbcType=JdbcType.INTEGER),
        @Result(column="shop_dsr", property="shopDsr", jdbcType=JdbcType.DECIMAL),
        @Result(column="shop_30_days_sales_volume", property="shop30DaysSalesVolume", jdbcType=JdbcType.BIGINT),
        @Result(column="activity_ids", property="activityIds", jdbcType=JdbcType.VARCHAR),
        @Result(column="activity_blacklist", property="activityBlacklist", jdbcType=JdbcType.VARCHAR),
        @Result(column="shop_activity_info", property="shopActivityInfo", jdbcType=JdbcType.VARCHAR),
        @Result(column="shop_warm_activity_info", property="shopWarmActivityInfo", jdbcType=JdbcType.VARCHAR),
        @Result(column="shop_part_activity_ids", property="shopPartActivityIds", jdbcType=JdbcType.VARCHAR),
        @Result(column="shop_invest_part_activity_ids", property="shopInvestPartActivityIds", jdbcType=JdbcType.VARCHAR),
        @Result(column="shop_invest_activity_ids", property="shopInvestActivityIds", jdbcType=JdbcType.VARCHAR),
        @Result(column="cross_shop_activity_ids", property="crossShopActivityIds", jdbcType=JdbcType.VARCHAR),
        @Result(column="cross_shop_activity_info", property="crossShopActivityInfo", jdbcType=JdbcType.VARCHAR),
        @Result(column="allowance_activity_ids", property="allowanceActivityIds", jdbcType=JdbcType.VARCHAR),
        @Result(column="original_price", property="originalPrice", jdbcType=JdbcType.BIGINT),
        @Result(column="price", property="price", jdbcType=JdbcType.BIGINT),
        @Result(column="big_promotion_price", property="bigPromotionPrice", jdbcType=JdbcType.BIGINT),
        @Result(column="daily_price", property="dailyPrice", jdbcType=JdbcType.BIGINT),
        @Result(column="vip_price", property="vipPrice", jdbcType=JdbcType.BIGINT),
        @Result(column="big_promotion_vip_price", property="bigPromotionVipPrice", jdbcType=JdbcType.BIGINT),
        @Result(column="daily_vip_price", property="dailyVipPrice", jdbcType=JdbcType.BIGINT),
        @Result(column="market_price", property="marketPrice", jdbcType=JdbcType.INTEGER),
        @Result(column="commission_total", property="commissionTotal", jdbcType=JdbcType.BIGINT),
        @Result(column="commission", property="commission", jdbcType=JdbcType.BIGINT),
        @Result(column="brokerage", property="brokerage", jdbcType=JdbcType.DECIMAL),
        @Result(column="lowest_price_last_7_days", property="lowestPriceLast7Days", jdbcType=JdbcType.BIGINT),
        @Result(column="lowest_price_last_15_days", property="lowestPriceLast15Days", jdbcType=JdbcType.BIGINT),
        @Result(column="lowest_price_last_30_days", property="lowestPriceLast30Days", jdbcType=JdbcType.BIGINT),
        @Result(column="in_big_promotion", property="inBigPromotion", jdbcType=JdbcType.TINYINT),
        @Result(column="goods_7_days_sales_volume", property="goods7DaysSalesVolume", jdbcType=JdbcType.BIGINT),
        @Result(column="goods_30_days_sales_volume", property="goods30DaysSalesVolume", jdbcType=JdbcType.BIGINT),
        @Result(column="goods_60_days_sales_volume", property="goods60DaysSalesVolume", jdbcType=JdbcType.BIGINT),
        @Result(column="goods_gmv_7", property="goodsGmv7", jdbcType=JdbcType.DECIMAL),
        @Result(column="goods_gmv_30", property="goodsGmv30", jdbcType=JdbcType.DECIMAL),
        @Result(column="goods_gmv_60", property="goodsGmv60", jdbcType=JdbcType.DECIMAL),
        @Result(column="goods_dsr", property="goodsDsr", jdbcType=JdbcType.DECIMAL),
        @Result(column="click_conver_rate_30", property="clickConverRate30", jdbcType=JdbcType.DECIMAL),
        @Result(column="purchase_conver_rate_30", property="purchaseConverRate30", jdbcType=JdbcType.DECIMAL),
        @Result(column="pay_conver_rate_30", property="payConverRate30", jdbcType=JdbcType.DECIMAL),
        @Result(column="reputation_rate", property="reputationRate", jdbcType=JdbcType.DECIMAL),
        @Result(column="reputation_rate30", property="reputationRate30", jdbcType=JdbcType.DECIMAL),
        @Result(column="buyer_number", property="buyerNumber", jdbcType=JdbcType.BIGINT),
        @Result(column="score", property="score", jdbcType=JdbcType.DECIMAL),
        @Result(column="weight", property="weight", jdbcType=JdbcType.INTEGER),
        @Result(column="prediction_score", property="predictionScore", jdbcType=JdbcType.DOUBLE),
        @Result(column="item_score", property="itemScore", jdbcType=JdbcType.DOUBLE),
        @Result(column="in_black_list", property="inBlackList", jdbcType=JdbcType.BIT),
        @Result(column="in_stock", property="inStock", jdbcType=JdbcType.BIT),
        @Result(column="in_feed", property="inFeed", jdbcType=JdbcType.TINYINT),
        @Result(column="sku_num", property="skuNum", jdbcType=JdbcType.SMALLINT),
        @Result(column="deleted", property="deleted", jdbcType=JdbcType.BIT),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="anchor_earning", property="anchorEarning", jdbcType=JdbcType.BIGINT),
        @Result(column="anchor_commission", property="anchorCommission", jdbcType=JdbcType.DECIMAL)
    })
    List<GoodsIndexData> selectByExampleWithRowbounds(GoodsIndexDataExample example, RowBounds rowBounds);

    @SelectProvider(type=GoodsIndexDataSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="item_id", property="itemId", jdbcType=JdbcType.BIGINT),
        @Result(column="long_title", property="longTitle", jdbcType=JdbcType.VARCHAR),
        @Result(column="short_title", property="shortTitle", jdbcType=JdbcType.VARCHAR),
        @Result(column="channel", property="channel", jdbcType=JdbcType.TINYINT),
        @Result(column="original_channel", property="originalChannel", jdbcType=JdbcType.TINYINT),
        @Result(column="shelf", property="shelf", jdbcType=JdbcType.TINYINT),
        @Result(column="status", property="status", jdbcType=JdbcType.TINYINT),
        @Result(column="item_type", property="itemType", jdbcType=JdbcType.TINYINT),
        @Result(column="item_sub_type", property="itemSubType", jdbcType=JdbcType.TINYINT),
        @Result(column="first_shelf_time", property="firstShelfTime", jdbcType=JdbcType.BIGINT),
        @Result(column="item_create_time", property="itemCreateTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="item_deliver_area_type", property="itemDeliverAreaType", jdbcType=JdbcType.BIT),
        @Result(column="white_image_url", property="whiteImageUrl", jdbcType=JdbcType.VARCHAR),
        @Result(column="white_image_width", property="whiteImageWidth", jdbcType=JdbcType.INTEGER),
        @Result(column="white_image_height", property="whiteImageHeight", jdbcType=JdbcType.INTEGER),
        @Result(column="major_image_url", property="majorImageUrl", jdbcType=JdbcType.VARCHAR),
        @Result(column="major_image_width", property="majorImageWidth", jdbcType=JdbcType.INTEGER),
        @Result(column="major_image_height", property="majorImageHeight", jdbcType=JdbcType.INTEGER),
        @Result(column="brand_id", property="brandId", jdbcType=JdbcType.INTEGER),
        @Result(column="brand_cn_name", property="brandCnName", jdbcType=JdbcType.VARCHAR),
        @Result(column="brand_en_name", property="brandEnName", jdbcType=JdbcType.VARCHAR),
        @Result(column="brand_state_id", property="brandStateId", jdbcType=JdbcType.INTEGER),
        @Result(column="brand_state_name", property="brandStateName", jdbcType=JdbcType.VARCHAR),
        @Result(column="brand_country_flag_url", property="brandCountryFlagUrl", jdbcType=JdbcType.VARCHAR),
        @Result(column="category_id", property="categoryId", jdbcType=JdbcType.INTEGER),
        @Result(column="category_id_path", property="categoryIdPath", jdbcType=JdbcType.VARCHAR),
        @Result(column="category_name", property="categoryName", jdbcType=JdbcType.VARCHAR),
        @Result(column="category_path_name", property="categoryPathName", jdbcType=JdbcType.VARCHAR),
        @Result(column="search_tags", property="searchTags", jdbcType=JdbcType.VARCHAR),
        @Result(column="goods_tags", property="goodsTags", jdbcType=JdbcType.VARCHAR),
        @Result(column="goods_properties", property="goodsProperties", jdbcType=JdbcType.VARCHAR),
        @Result(column="shop_id", property="shopId", jdbcType=JdbcType.BIGINT),
        @Result(column="shop_name", property="shopName", jdbcType=JdbcType.VARCHAR),
        @Result(column="shop_class_id", property="shopClassId", jdbcType=JdbcType.VARCHAR),
        @Result(column="shop_type", property="shopType", jdbcType=JdbcType.BIT),
        @Result(column="registration_address_type", property="registrationAddressType", jdbcType=JdbcType.BIT),
        @Result(column="shop_level", property="shopLevel", jdbcType=JdbcType.BIT),
        @Result(column="shop_major_category_ids", property="shopMajorCategoryIds", jdbcType=JdbcType.VARCHAR),
        @Result(column="shop_gmv_30", property="shopGmv30", jdbcType=JdbcType.DECIMAL),
        @Result(column="shop_gmv_90", property="shopGmv90", jdbcType=JdbcType.DECIMAL),
        @Result(column="shop_aftersale_rate_30", property="shopAftersaleRate30", jdbcType=JdbcType.DECIMAL),
        @Result(column="shop_open_days", property="shopOpenDays", jdbcType=JdbcType.INTEGER),
        @Result(column="shop_dsr", property="shopDsr", jdbcType=JdbcType.DECIMAL),
        @Result(column="shop_30_days_sales_volume", property="shop30DaysSalesVolume", jdbcType=JdbcType.BIGINT),
        @Result(column="activity_ids", property="activityIds", jdbcType=JdbcType.VARCHAR),
        @Result(column="activity_blacklist", property="activityBlacklist", jdbcType=JdbcType.VARCHAR),
        @Result(column="shop_activity_info", property="shopActivityInfo", jdbcType=JdbcType.VARCHAR),
        @Result(column="shop_warm_activity_info", property="shopWarmActivityInfo", jdbcType=JdbcType.VARCHAR),
        @Result(column="shop_part_activity_ids", property="shopPartActivityIds", jdbcType=JdbcType.VARCHAR),
        @Result(column="shop_invest_part_activity_ids", property="shopInvestPartActivityIds", jdbcType=JdbcType.VARCHAR),
        @Result(column="shop_invest_activity_ids", property="shopInvestActivityIds", jdbcType=JdbcType.VARCHAR),
        @Result(column="cross_shop_activity_ids", property="crossShopActivityIds", jdbcType=JdbcType.VARCHAR),
        @Result(column="cross_shop_activity_info", property="crossShopActivityInfo", jdbcType=JdbcType.VARCHAR),
        @Result(column="allowance_activity_ids", property="allowanceActivityIds", jdbcType=JdbcType.VARCHAR),
        @Result(column="original_price", property="originalPrice", jdbcType=JdbcType.BIGINT),
        @Result(column="price", property="price", jdbcType=JdbcType.BIGINT),
        @Result(column="big_promotion_price", property="bigPromotionPrice", jdbcType=JdbcType.BIGINT),
        @Result(column="daily_price", property="dailyPrice", jdbcType=JdbcType.BIGINT),
        @Result(column="vip_price", property="vipPrice", jdbcType=JdbcType.BIGINT),
        @Result(column="big_promotion_vip_price", property="bigPromotionVipPrice", jdbcType=JdbcType.BIGINT),
        @Result(column="daily_vip_price", property="dailyVipPrice", jdbcType=JdbcType.BIGINT),
        @Result(column="market_price", property="marketPrice", jdbcType=JdbcType.INTEGER),
        @Result(column="commission_total", property="commissionTotal", jdbcType=JdbcType.BIGINT),
        @Result(column="commission", property="commission", jdbcType=JdbcType.BIGINT),
        @Result(column="brokerage", property="brokerage", jdbcType=JdbcType.DECIMAL),
        @Result(column="lowest_price_last_7_days", property="lowestPriceLast7Days", jdbcType=JdbcType.BIGINT),
        @Result(column="lowest_price_last_15_days", property="lowestPriceLast15Days", jdbcType=JdbcType.BIGINT),
        @Result(column="lowest_price_last_30_days", property="lowestPriceLast30Days", jdbcType=JdbcType.BIGINT),
        @Result(column="in_big_promotion", property="inBigPromotion", jdbcType=JdbcType.TINYINT),
        @Result(column="goods_7_days_sales_volume", property="goods7DaysSalesVolume", jdbcType=JdbcType.BIGINT),
        @Result(column="goods_30_days_sales_volume", property="goods30DaysSalesVolume", jdbcType=JdbcType.BIGINT),
        @Result(column="goods_60_days_sales_volume", property="goods60DaysSalesVolume", jdbcType=JdbcType.BIGINT),
        @Result(column="goods_gmv_7", property="goodsGmv7", jdbcType=JdbcType.DECIMAL),
        @Result(column="goods_gmv_30", property="goodsGmv30", jdbcType=JdbcType.DECIMAL),
        @Result(column="goods_gmv_60", property="goodsGmv60", jdbcType=JdbcType.DECIMAL),
        @Result(column="goods_dsr", property="goodsDsr", jdbcType=JdbcType.DECIMAL),
        @Result(column="click_conver_rate_30", property="clickConverRate30", jdbcType=JdbcType.DECIMAL),
        @Result(column="purchase_conver_rate_30", property="purchaseConverRate30", jdbcType=JdbcType.DECIMAL),
        @Result(column="pay_conver_rate_30", property="payConverRate30", jdbcType=JdbcType.DECIMAL),
        @Result(column="reputation_rate", property="reputationRate", jdbcType=JdbcType.DECIMAL),
        @Result(column="reputation_rate30", property="reputationRate30", jdbcType=JdbcType.DECIMAL),
        @Result(column="buyer_number", property="buyerNumber", jdbcType=JdbcType.BIGINT),
        @Result(column="score", property="score", jdbcType=JdbcType.DECIMAL),
        @Result(column="weight", property="weight", jdbcType=JdbcType.INTEGER),
        @Result(column="prediction_score", property="predictionScore", jdbcType=JdbcType.DOUBLE),
        @Result(column="item_score", property="itemScore", jdbcType=JdbcType.DOUBLE),
        @Result(column="in_black_list", property="inBlackList", jdbcType=JdbcType.BIT),
        @Result(column="in_stock", property="inStock", jdbcType=JdbcType.BIT),
        @Result(column="in_feed", property="inFeed", jdbcType=JdbcType.TINYINT),
        @Result(column="sku_num", property="skuNum", jdbcType=JdbcType.SMALLINT),
        @Result(column="deleted", property="deleted", jdbcType=JdbcType.BIT),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="anchor_earning", property="anchorEarning", jdbcType=JdbcType.BIGINT),
        @Result(column="anchor_commission", property="anchorCommission", jdbcType=JdbcType.DECIMAL)
    })
    List<GoodsIndexData> selectByExample(GoodsIndexDataExample example);

    @Select({
        "select",
        "id, item_id, long_title, short_title, channel, original_channel, shelf, status, ",
        "item_type, item_sub_type, first_shelf_time, item_create_time, item_deliver_area_type, ",
        "white_image_url, white_image_width, white_image_height, major_image_url, major_image_width, ",
        "major_image_height, brand_id, brand_cn_name, brand_en_name, brand_state_id, ",
        "brand_state_name, brand_country_flag_url, category_id, category_id_path, category_name, ",
        "category_path_name, search_tags, goods_tags, goods_properties, shop_id, shop_name, ",
        "shop_class_id, shop_type, registration_address_type, shop_level, shop_major_category_ids, ",
        "shop_gmv_30, shop_gmv_90, shop_aftersale_rate_30, shop_open_days, shop_dsr, ",
        "shop_30_days_sales_volume, activity_ids, activity_blacklist, shop_activity_info, ",
        "shop_warm_activity_info, shop_part_activity_ids, shop_invest_part_activity_ids, ",
        "shop_invest_activity_ids, cross_shop_activity_ids, cross_shop_activity_info, ",
        "allowance_activity_ids, original_price, price, big_promotion_price, daily_price, ",
        "vip_price, big_promotion_vip_price, daily_vip_price, market_price, commission_total, ",
        "commission, brokerage, lowest_price_last_7_days, lowest_price_last_15_days, ",
        "lowest_price_last_30_days, in_big_promotion, goods_7_days_sales_volume, goods_30_days_sales_volume, ",
        "goods_60_days_sales_volume, goods_gmv_7, goods_gmv_30, goods_gmv_60, goods_dsr, ",
        "click_conver_rate_30, purchase_conver_rate_30, pay_conver_rate_30, reputation_rate, ",
        "reputation_rate30, buyer_number, score, weight, prediction_score, item_score, ",
        "in_black_list, in_stock, in_feed, sku_num, deleted, create_time, update_time, ",
        "anchor_earning, anchor_commission, channel_data, shop_tags, activity_tags, whole_sale_discounts, ",
        "big_promotion_price_info, advance_sale_info, embedding",
        "from goods_index_data",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="item_id", property="itemId", jdbcType=JdbcType.BIGINT),
        @Result(column="long_title", property="longTitle", jdbcType=JdbcType.VARCHAR),
        @Result(column="short_title", property="shortTitle", jdbcType=JdbcType.VARCHAR),
        @Result(column="channel", property="channel", jdbcType=JdbcType.TINYINT),
        @Result(column="original_channel", property="originalChannel", jdbcType=JdbcType.TINYINT),
        @Result(column="shelf", property="shelf", jdbcType=JdbcType.TINYINT),
        @Result(column="status", property="status", jdbcType=JdbcType.TINYINT),
        @Result(column="item_type", property="itemType", jdbcType=JdbcType.TINYINT),
        @Result(column="item_sub_type", property="itemSubType", jdbcType=JdbcType.TINYINT),
        @Result(column="first_shelf_time", property="firstShelfTime", jdbcType=JdbcType.BIGINT),
        @Result(column="item_create_time", property="itemCreateTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="item_deliver_area_type", property="itemDeliverAreaType", jdbcType=JdbcType.BIT),
        @Result(column="white_image_url", property="whiteImageUrl", jdbcType=JdbcType.VARCHAR),
        @Result(column="white_image_width", property="whiteImageWidth", jdbcType=JdbcType.INTEGER),
        @Result(column="white_image_height", property="whiteImageHeight", jdbcType=JdbcType.INTEGER),
        @Result(column="major_image_url", property="majorImageUrl", jdbcType=JdbcType.VARCHAR),
        @Result(column="major_image_width", property="majorImageWidth", jdbcType=JdbcType.INTEGER),
        @Result(column="major_image_height", property="majorImageHeight", jdbcType=JdbcType.INTEGER),
        @Result(column="brand_id", property="brandId", jdbcType=JdbcType.INTEGER),
        @Result(column="brand_cn_name", property="brandCnName", jdbcType=JdbcType.VARCHAR),
        @Result(column="brand_en_name", property="brandEnName", jdbcType=JdbcType.VARCHAR),
        @Result(column="brand_state_id", property="brandStateId", jdbcType=JdbcType.INTEGER),
        @Result(column="brand_state_name", property="brandStateName", jdbcType=JdbcType.VARCHAR),
        @Result(column="brand_country_flag_url", property="brandCountryFlagUrl", jdbcType=JdbcType.VARCHAR),
        @Result(column="category_id", property="categoryId", jdbcType=JdbcType.INTEGER),
        @Result(column="category_id_path", property="categoryIdPath", jdbcType=JdbcType.VARCHAR),
        @Result(column="category_name", property="categoryName", jdbcType=JdbcType.VARCHAR),
        @Result(column="category_path_name", property="categoryPathName", jdbcType=JdbcType.VARCHAR),
        @Result(column="search_tags", property="searchTags", jdbcType=JdbcType.VARCHAR),
        @Result(column="goods_tags", property="goodsTags", jdbcType=JdbcType.VARCHAR),
        @Result(column="goods_properties", property="goodsProperties", jdbcType=JdbcType.VARCHAR),
        @Result(column="shop_id", property="shopId", jdbcType=JdbcType.BIGINT),
        @Result(column="shop_name", property="shopName", jdbcType=JdbcType.VARCHAR),
        @Result(column="shop_class_id", property="shopClassId", jdbcType=JdbcType.VARCHAR),
        @Result(column="shop_type", property="shopType", jdbcType=JdbcType.BIT),
        @Result(column="registration_address_type", property="registrationAddressType", jdbcType=JdbcType.BIT),
        @Result(column="shop_level", property="shopLevel", jdbcType=JdbcType.BIT),
        @Result(column="shop_major_category_ids", property="shopMajorCategoryIds", jdbcType=JdbcType.VARCHAR),
        @Result(column="shop_gmv_30", property="shopGmv30", jdbcType=JdbcType.DECIMAL),
        @Result(column="shop_gmv_90", property="shopGmv90", jdbcType=JdbcType.DECIMAL),
        @Result(column="shop_aftersale_rate_30", property="shopAftersaleRate30", jdbcType=JdbcType.DECIMAL),
        @Result(column="shop_open_days", property="shopOpenDays", jdbcType=JdbcType.INTEGER),
        @Result(column="shop_dsr", property="shopDsr", jdbcType=JdbcType.DECIMAL),
        @Result(column="shop_30_days_sales_volume", property="shop30DaysSalesVolume", jdbcType=JdbcType.BIGINT),
        @Result(column="activity_ids", property="activityIds", jdbcType=JdbcType.VARCHAR),
        @Result(column="activity_blacklist", property="activityBlacklist", jdbcType=JdbcType.VARCHAR),
        @Result(column="shop_activity_info", property="shopActivityInfo", jdbcType=JdbcType.VARCHAR),
        @Result(column="shop_warm_activity_info", property="shopWarmActivityInfo", jdbcType=JdbcType.VARCHAR),
        @Result(column="shop_part_activity_ids", property="shopPartActivityIds", jdbcType=JdbcType.VARCHAR),
        @Result(column="shop_invest_part_activity_ids", property="shopInvestPartActivityIds", jdbcType=JdbcType.VARCHAR),
        @Result(column="shop_invest_activity_ids", property="shopInvestActivityIds", jdbcType=JdbcType.VARCHAR),
        @Result(column="cross_shop_activity_ids", property="crossShopActivityIds", jdbcType=JdbcType.VARCHAR),
        @Result(column="cross_shop_activity_info", property="crossShopActivityInfo", jdbcType=JdbcType.VARCHAR),
        @Result(column="allowance_activity_ids", property="allowanceActivityIds", jdbcType=JdbcType.VARCHAR),
        @Result(column="original_price", property="originalPrice", jdbcType=JdbcType.BIGINT),
        @Result(column="price", property="price", jdbcType=JdbcType.BIGINT),
        @Result(column="big_promotion_price", property="bigPromotionPrice", jdbcType=JdbcType.BIGINT),
        @Result(column="daily_price", property="dailyPrice", jdbcType=JdbcType.BIGINT),
        @Result(column="vip_price", property="vipPrice", jdbcType=JdbcType.BIGINT),
        @Result(column="big_promotion_vip_price", property="bigPromotionVipPrice", jdbcType=JdbcType.BIGINT),
        @Result(column="daily_vip_price", property="dailyVipPrice", jdbcType=JdbcType.BIGINT),
        @Result(column="market_price", property="marketPrice", jdbcType=JdbcType.INTEGER),
        @Result(column="commission_total", property="commissionTotal", jdbcType=JdbcType.BIGINT),
        @Result(column="commission", property="commission", jdbcType=JdbcType.BIGINT),
        @Result(column="brokerage", property="brokerage", jdbcType=JdbcType.DECIMAL),
        @Result(column="lowest_price_last_7_days", property="lowestPriceLast7Days", jdbcType=JdbcType.BIGINT),
        @Result(column="lowest_price_last_15_days", property="lowestPriceLast15Days", jdbcType=JdbcType.BIGINT),
        @Result(column="lowest_price_last_30_days", property="lowestPriceLast30Days", jdbcType=JdbcType.BIGINT),
        @Result(column="in_big_promotion", property="inBigPromotion", jdbcType=JdbcType.TINYINT),
        @Result(column="goods_7_days_sales_volume", property="goods7DaysSalesVolume", jdbcType=JdbcType.BIGINT),
        @Result(column="goods_30_days_sales_volume", property="goods30DaysSalesVolume", jdbcType=JdbcType.BIGINT),
        @Result(column="goods_60_days_sales_volume", property="goods60DaysSalesVolume", jdbcType=JdbcType.BIGINT),
        @Result(column="goods_gmv_7", property="goodsGmv7", jdbcType=JdbcType.DECIMAL),
        @Result(column="goods_gmv_30", property="goodsGmv30", jdbcType=JdbcType.DECIMAL),
        @Result(column="goods_gmv_60", property="goodsGmv60", jdbcType=JdbcType.DECIMAL),
        @Result(column="goods_dsr", property="goodsDsr", jdbcType=JdbcType.DECIMAL),
        @Result(column="click_conver_rate_30", property="clickConverRate30", jdbcType=JdbcType.DECIMAL),
        @Result(column="purchase_conver_rate_30", property="purchaseConverRate30", jdbcType=JdbcType.DECIMAL),
        @Result(column="pay_conver_rate_30", property="payConverRate30", jdbcType=JdbcType.DECIMAL),
        @Result(column="reputation_rate", property="reputationRate", jdbcType=JdbcType.DECIMAL),
        @Result(column="reputation_rate30", property="reputationRate30", jdbcType=JdbcType.DECIMAL),
        @Result(column="buyer_number", property="buyerNumber", jdbcType=JdbcType.BIGINT),
        @Result(column="score", property="score", jdbcType=JdbcType.DECIMAL),
        @Result(column="weight", property="weight", jdbcType=JdbcType.INTEGER),
        @Result(column="prediction_score", property="predictionScore", jdbcType=JdbcType.DOUBLE),
        @Result(column="item_score", property="itemScore", jdbcType=JdbcType.DOUBLE),
        @Result(column="in_black_list", property="inBlackList", jdbcType=JdbcType.BIT),
        @Result(column="in_stock", property="inStock", jdbcType=JdbcType.BIT),
        @Result(column="in_feed", property="inFeed", jdbcType=JdbcType.TINYINT),
        @Result(column="sku_num", property="skuNum", jdbcType=JdbcType.SMALLINT),
        @Result(column="deleted", property="deleted", jdbcType=JdbcType.BIT),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="anchor_earning", property="anchorEarning", jdbcType=JdbcType.BIGINT),
        @Result(column="anchor_commission", property="anchorCommission", jdbcType=JdbcType.DECIMAL),
        @Result(column="channel_data", property="channelData", jdbcType=JdbcType.LONGVARCHAR),
        @Result(column="shop_tags", property="shopTags", jdbcType=JdbcType.LONGVARCHAR),
        @Result(column="activity_tags", property="activityTags", jdbcType=JdbcType.LONGVARCHAR),
        @Result(column="whole_sale_discounts", property="wholeSaleDiscounts", jdbcType=JdbcType.LONGVARCHAR),
        @Result(column="big_promotion_price_info", property="bigPromotionPriceInfo", jdbcType=JdbcType.LONGVARCHAR),
        @Result(column="advance_sale_info", property="advanceSaleInfo", jdbcType=JdbcType.LONGVARCHAR),
        @Result(column="embedding", property="embedding", jdbcType=JdbcType.LONGVARCHAR)
    })
    GoodsIndexDataWithBLOBs selectByPrimaryKey(Long id);

    @UpdateProvider(type=GoodsIndexDataSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") GoodsIndexDataWithBLOBs record, @Param("example") GoodsIndexDataExample example);

    @UpdateProvider(type=GoodsIndexDataSqlProvider.class, method="updateByExampleWithBLOBs")
    int updateByExampleWithBLOBs(@Param("record") GoodsIndexDataWithBLOBs record, @Param("example") GoodsIndexDataExample example);

    @UpdateProvider(type=GoodsIndexDataSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") GoodsIndexData record, @Param("example") GoodsIndexDataExample example);

    @UpdateProvider(type=GoodsIndexDataSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(GoodsIndexDataWithBLOBs record);

    @Update({
        "update goods_index_data",
        "set item_id = #{itemId,jdbcType=BIGINT},",
          "long_title = #{longTitle,jdbcType=VARCHAR},",
          "short_title = #{shortTitle,jdbcType=VARCHAR},",
          "channel = #{channel,jdbcType=TINYINT},",
          "original_channel = #{originalChannel,jdbcType=TINYINT},",
          "shelf = #{shelf,jdbcType=TINYINT},",
          "status = #{status,jdbcType=TINYINT},",
          "item_type = #{itemType,jdbcType=TINYINT},",
          "item_sub_type = #{itemSubType,jdbcType=TINYINT},",
          "first_shelf_time = #{firstShelfTime,jdbcType=BIGINT},",
          "item_create_time = #{itemCreateTime,jdbcType=TIMESTAMP},",
          "item_deliver_area_type = #{itemDeliverAreaType,jdbcType=BIT},",
          "white_image_url = #{whiteImageUrl,jdbcType=VARCHAR},",
          "white_image_width = #{whiteImageWidth,jdbcType=INTEGER},",
          "white_image_height = #{whiteImageHeight,jdbcType=INTEGER},",
          "major_image_url = #{majorImageUrl,jdbcType=VARCHAR},",
          "major_image_width = #{majorImageWidth,jdbcType=INTEGER},",
          "major_image_height = #{majorImageHeight,jdbcType=INTEGER},",
          "brand_id = #{brandId,jdbcType=INTEGER},",
          "brand_cn_name = #{brandCnName,jdbcType=VARCHAR},",
          "brand_en_name = #{brandEnName,jdbcType=VARCHAR},",
          "brand_state_id = #{brandStateId,jdbcType=INTEGER},",
          "brand_state_name = #{brandStateName,jdbcType=VARCHAR},",
          "brand_country_flag_url = #{brandCountryFlagUrl,jdbcType=VARCHAR},",
          "category_id = #{categoryId,jdbcType=INTEGER},",
          "category_id_path = #{categoryIdPath,jdbcType=VARCHAR},",
          "category_name = #{categoryName,jdbcType=VARCHAR},",
          "category_path_name = #{categoryPathName,jdbcType=VARCHAR},",
          "search_tags = #{searchTags,jdbcType=VARCHAR},",
          "goods_tags = #{goodsTags,jdbcType=VARCHAR},",
          "goods_properties = #{goodsProperties,jdbcType=VARCHAR},",
          "shop_id = #{shopId,jdbcType=BIGINT},",
          "shop_name = #{shopName,jdbcType=VARCHAR},",
          "shop_class_id = #{shopClassId,jdbcType=VARCHAR},",
          "shop_type = #{shopType,jdbcType=BIT},",
          "registration_address_type = #{registrationAddressType,jdbcType=BIT},",
          "shop_level = #{shopLevel,jdbcType=BIT},",
          "shop_major_category_ids = #{shopMajorCategoryIds,jdbcType=VARCHAR},",
          "shop_gmv_30 = #{shopGmv30,jdbcType=DECIMAL},",
          "shop_gmv_90 = #{shopGmv90,jdbcType=DECIMAL},",
          "shop_aftersale_rate_30 = #{shopAftersaleRate30,jdbcType=DECIMAL},",
          "shop_open_days = #{shopOpenDays,jdbcType=INTEGER},",
          "shop_dsr = #{shopDsr,jdbcType=DECIMAL},",
          "shop_30_days_sales_volume = #{shop30DaysSalesVolume,jdbcType=BIGINT},",
          "activity_ids = #{activityIds,jdbcType=VARCHAR},",
          "activity_blacklist = #{activityBlacklist,jdbcType=VARCHAR},",
          "shop_activity_info = #{shopActivityInfo,jdbcType=VARCHAR},",
          "shop_warm_activity_info = #{shopWarmActivityInfo,jdbcType=VARCHAR},",
          "shop_part_activity_ids = #{shopPartActivityIds,jdbcType=VARCHAR},",
          "shop_invest_part_activity_ids = #{shopInvestPartActivityIds,jdbcType=VARCHAR},",
          "shop_invest_activity_ids = #{shopInvestActivityIds,jdbcType=VARCHAR},",
          "cross_shop_activity_ids = #{crossShopActivityIds,jdbcType=VARCHAR},",
          "cross_shop_activity_info = #{crossShopActivityInfo,jdbcType=VARCHAR},",
          "allowance_activity_ids = #{allowanceActivityIds,jdbcType=VARCHAR},",
          "original_price = #{originalPrice,jdbcType=BIGINT},",
          "price = #{price,jdbcType=BIGINT},",
          "big_promotion_price = #{bigPromotionPrice,jdbcType=BIGINT},",
          "daily_price = #{dailyPrice,jdbcType=BIGINT},",
          "vip_price = #{vipPrice,jdbcType=BIGINT},",
          "big_promotion_vip_price = #{bigPromotionVipPrice,jdbcType=BIGINT},",
          "daily_vip_price = #{dailyVipPrice,jdbcType=BIGINT},",
          "market_price = #{marketPrice,jdbcType=INTEGER},",
          "commission_total = #{commissionTotal,jdbcType=BIGINT},",
          "commission = #{commission,jdbcType=BIGINT},",
          "brokerage = #{brokerage,jdbcType=DECIMAL},",
          "lowest_price_last_7_days = #{lowestPriceLast7Days,jdbcType=BIGINT},",
          "lowest_price_last_15_days = #{lowestPriceLast15Days,jdbcType=BIGINT},",
          "lowest_price_last_30_days = #{lowestPriceLast30Days,jdbcType=BIGINT},",
          "in_big_promotion = #{inBigPromotion,jdbcType=TINYINT},",
          "goods_7_days_sales_volume = #{goods7DaysSalesVolume,jdbcType=BIGINT},",
          "goods_30_days_sales_volume = #{goods30DaysSalesVolume,jdbcType=BIGINT},",
          "goods_60_days_sales_volume = #{goods60DaysSalesVolume,jdbcType=BIGINT},",
          "goods_gmv_7 = #{goodsGmv7,jdbcType=DECIMAL},",
          "goods_gmv_30 = #{goodsGmv30,jdbcType=DECIMAL},",
          "goods_gmv_60 = #{goodsGmv60,jdbcType=DECIMAL},",
          "goods_dsr = #{goodsDsr,jdbcType=DECIMAL},",
          "click_conver_rate_30 = #{clickConverRate30,jdbcType=DECIMAL},",
          "purchase_conver_rate_30 = #{purchaseConverRate30,jdbcType=DECIMAL},",
          "pay_conver_rate_30 = #{payConverRate30,jdbcType=DECIMAL},",
          "reputation_rate = #{reputationRate,jdbcType=DECIMAL},",
          "reputation_rate30 = #{reputationRate30,jdbcType=DECIMAL},",
          "buyer_number = #{buyerNumber,jdbcType=BIGINT},",
          "score = #{score,jdbcType=DECIMAL},",
          "weight = #{weight,jdbcType=INTEGER},",
          "prediction_score = #{predictionScore,jdbcType=DOUBLE},",
          "item_score = #{itemScore,jdbcType=DOUBLE},",
          "in_black_list = #{inBlackList,jdbcType=BIT},",
          "in_stock = #{inStock,jdbcType=BIT},",
          "in_feed = #{inFeed,jdbcType=TINYINT},",
          "sku_num = #{skuNum,jdbcType=SMALLINT},",
          "deleted = #{deleted,jdbcType=BIT},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP},",
          "anchor_earning = #{anchorEarning,jdbcType=BIGINT},",
          "anchor_commission = #{anchorCommission,jdbcType=DECIMAL},",
          "channel_data = #{channelData,jdbcType=LONGVARCHAR},",
          "shop_tags = #{shopTags,jdbcType=LONGVARCHAR},",
          "activity_tags = #{activityTags,jdbcType=LONGVARCHAR},",
          "whole_sale_discounts = #{wholeSaleDiscounts,jdbcType=LONGVARCHAR},",
          "big_promotion_price_info = #{bigPromotionPriceInfo,jdbcType=LONGVARCHAR},",
          "advance_sale_info = #{advanceSaleInfo,jdbcType=LONGVARCHAR},",
          "embedding = #{embedding,jdbcType=LONGVARCHAR}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKeyWithBLOBs(GoodsIndexDataWithBLOBs record);

    @Update({
        "update goods_index_data",
        "set item_id = #{itemId,jdbcType=BIGINT},",
          "long_title = #{longTitle,jdbcType=VARCHAR},",
          "short_title = #{shortTitle,jdbcType=VARCHAR},",
          "channel = #{channel,jdbcType=TINYINT},",
          "original_channel = #{originalChannel,jdbcType=TINYINT},",
          "shelf = #{shelf,jdbcType=TINYINT},",
          "status = #{status,jdbcType=TINYINT},",
          "item_type = #{itemType,jdbcType=TINYINT},",
          "item_sub_type = #{itemSubType,jdbcType=TINYINT},",
          "first_shelf_time = #{firstShelfTime,jdbcType=BIGINT},",
          "item_create_time = #{itemCreateTime,jdbcType=TIMESTAMP},",
          "item_deliver_area_type = #{itemDeliverAreaType,jdbcType=BIT},",
          "white_image_url = #{whiteImageUrl,jdbcType=VARCHAR},",
          "white_image_width = #{whiteImageWidth,jdbcType=INTEGER},",
          "white_image_height = #{whiteImageHeight,jdbcType=INTEGER},",
          "major_image_url = #{majorImageUrl,jdbcType=VARCHAR},",
          "major_image_width = #{majorImageWidth,jdbcType=INTEGER},",
          "major_image_height = #{majorImageHeight,jdbcType=INTEGER},",
          "brand_id = #{brandId,jdbcType=INTEGER},",
          "brand_cn_name = #{brandCnName,jdbcType=VARCHAR},",
          "brand_en_name = #{brandEnName,jdbcType=VARCHAR},",
          "brand_state_id = #{brandStateId,jdbcType=INTEGER},",
          "brand_state_name = #{brandStateName,jdbcType=VARCHAR},",
          "brand_country_flag_url = #{brandCountryFlagUrl,jdbcType=VARCHAR},",
          "category_id = #{categoryId,jdbcType=INTEGER},",
          "category_id_path = #{categoryIdPath,jdbcType=VARCHAR},",
          "category_name = #{categoryName,jdbcType=VARCHAR},",
          "category_path_name = #{categoryPathName,jdbcType=VARCHAR},",
          "search_tags = #{searchTags,jdbcType=VARCHAR},",
          "goods_tags = #{goodsTags,jdbcType=VARCHAR},",
          "goods_properties = #{goodsProperties,jdbcType=VARCHAR},",
          "shop_id = #{shopId,jdbcType=BIGINT},",
          "shop_name = #{shopName,jdbcType=VARCHAR},",
          "shop_class_id = #{shopClassId,jdbcType=VARCHAR},",
          "shop_type = #{shopType,jdbcType=BIT},",
          "registration_address_type = #{registrationAddressType,jdbcType=BIT},",
          "shop_level = #{shopLevel,jdbcType=BIT},",
          "shop_major_category_ids = #{shopMajorCategoryIds,jdbcType=VARCHAR},",
          "shop_gmv_30 = #{shopGmv30,jdbcType=DECIMAL},",
          "shop_gmv_90 = #{shopGmv90,jdbcType=DECIMAL},",
          "shop_aftersale_rate_30 = #{shopAftersaleRate30,jdbcType=DECIMAL},",
          "shop_open_days = #{shopOpenDays,jdbcType=INTEGER},",
          "shop_dsr = #{shopDsr,jdbcType=DECIMAL},",
          "shop_30_days_sales_volume = #{shop30DaysSalesVolume,jdbcType=BIGINT},",
          "activity_ids = #{activityIds,jdbcType=VARCHAR},",
          "activity_blacklist = #{activityBlacklist,jdbcType=VARCHAR},",
          "shop_activity_info = #{shopActivityInfo,jdbcType=VARCHAR},",
          "shop_warm_activity_info = #{shopWarmActivityInfo,jdbcType=VARCHAR},",
          "shop_part_activity_ids = #{shopPartActivityIds,jdbcType=VARCHAR},",
          "shop_invest_part_activity_ids = #{shopInvestPartActivityIds,jdbcType=VARCHAR},",
          "shop_invest_activity_ids = #{shopInvestActivityIds,jdbcType=VARCHAR},",
          "cross_shop_activity_ids = #{crossShopActivityIds,jdbcType=VARCHAR},",
          "cross_shop_activity_info = #{crossShopActivityInfo,jdbcType=VARCHAR},",
          "allowance_activity_ids = #{allowanceActivityIds,jdbcType=VARCHAR},",
          "original_price = #{originalPrice,jdbcType=BIGINT},",
          "price = #{price,jdbcType=BIGINT},",
          "big_promotion_price = #{bigPromotionPrice,jdbcType=BIGINT},",
          "daily_price = #{dailyPrice,jdbcType=BIGINT},",
          "vip_price = #{vipPrice,jdbcType=BIGINT},",
          "big_promotion_vip_price = #{bigPromotionVipPrice,jdbcType=BIGINT},",
          "daily_vip_price = #{dailyVipPrice,jdbcType=BIGINT},",
          "market_price = #{marketPrice,jdbcType=INTEGER},",
          "commission_total = #{commissionTotal,jdbcType=BIGINT},",
          "commission = #{commission,jdbcType=BIGINT},",
          "brokerage = #{brokerage,jdbcType=DECIMAL},",
          "lowest_price_last_7_days = #{lowestPriceLast7Days,jdbcType=BIGINT},",
          "lowest_price_last_15_days = #{lowestPriceLast15Days,jdbcType=BIGINT},",
          "lowest_price_last_30_days = #{lowestPriceLast30Days,jdbcType=BIGINT},",
          "in_big_promotion = #{inBigPromotion,jdbcType=TINYINT},",
          "goods_7_days_sales_volume = #{goods7DaysSalesVolume,jdbcType=BIGINT},",
          "goods_30_days_sales_volume = #{goods30DaysSalesVolume,jdbcType=BIGINT},",
          "goods_60_days_sales_volume = #{goods60DaysSalesVolume,jdbcType=BIGINT},",
          "goods_gmv_7 = #{goodsGmv7,jdbcType=DECIMAL},",
          "goods_gmv_30 = #{goodsGmv30,jdbcType=DECIMAL},",
          "goods_gmv_60 = #{goodsGmv60,jdbcType=DECIMAL},",
          "goods_dsr = #{goodsDsr,jdbcType=DECIMAL},",
          "click_conver_rate_30 = #{clickConverRate30,jdbcType=DECIMAL},",
          "purchase_conver_rate_30 = #{purchaseConverRate30,jdbcType=DECIMAL},",
          "pay_conver_rate_30 = #{payConverRate30,jdbcType=DECIMAL},",
          "reputation_rate = #{reputationRate,jdbcType=DECIMAL},",
          "reputation_rate30 = #{reputationRate30,jdbcType=DECIMAL},",
          "buyer_number = #{buyerNumber,jdbcType=BIGINT},",
          "score = #{score,jdbcType=DECIMAL},",
          "weight = #{weight,jdbcType=INTEGER},",
          "prediction_score = #{predictionScore,jdbcType=DOUBLE},",
          "item_score = #{itemScore,jdbcType=DOUBLE},",
          "in_black_list = #{inBlackList,jdbcType=BIT},",
          "in_stock = #{inStock,jdbcType=BIT},",
          "in_feed = #{inFeed,jdbcType=TINYINT},",
          "sku_num = #{skuNum,jdbcType=SMALLINT},",
          "deleted = #{deleted,jdbcType=BIT},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP},",
          "anchor_earning = #{anchorEarning,jdbcType=BIGINT},",
          "anchor_commission = #{anchorCommission,jdbcType=DECIMAL}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(GoodsIndexData record);
}